# -*- coding: utf-8 -*-
"""Rubrica2024-2.ipynb

Automatically generated by Colab.

**Rubrica algoritmo 2024-2**

*Presentado por:*

*Jhon Alzate & Ivan Cuentas*

Punto 1

**Sistema de Gestión de Inventario de una Tienda**
"""

# Definimos la clase Producto para representar cada producto en el inventario
class Producto:
    def __init__(self, id_producto, nombre, cantidad, precio_unitario):
        self.id_producto = id_producto
        self.nombre = nombre
        self.cantidad = cantidad
        self.precio_unitario = precio_unitario

    def valor_total(self):
        return self.cantidad * self.precio_unitario

# Función para ingresar productos al inventario
def ingresar_producto(inventario, id_producto):
    nombre = input(f"Introduce el nombre del producto (ID {id_producto}): ")
    while True:
        try:
            cantidad = int(input(f"Introduce la cantidad de {nombre}: "))
            if cantidad <= 0:
                print("La cantidad debe ser mayor que cero.")
            else:
                break
        except ValueError:
            print("Por favor, ingrese un número válido para la cantidad.")

    while True:
        try:
            precio_unitario = float(input(f"Introduce el precio unitario de {nombre}: "))
            if precio_unitario < 0:
                print("El precio unitario no puede ser negativo.")
            else:
                break
        except ValueError:
            print("Por favor, ingrese un número válido para el precio unitario.")

    # Crear el producto y agregarlo al inventario
    producto = Producto(id_producto, nombre, cantidad, precio_unitario)
    inventario[id_producto] = producto
    print(f"Producto {nombre} registrado con éxito.")

# Función para mostrar el inventario
def mostrar_inventario(inventario):
    if not inventario:
        print("El inventario está vacío.")
    else:
        print("Inventario de productos:")
        for producto in inventario.values():
            print(f"ID: {producto.id_producto}, Nombre: {producto.nombre}, "
                  f"Cantidad: {producto.cantidad}, Precio Unitario: {producto.precio_unitario:.2f}, "
                  f"Valor Total: {producto.valor_total():.2f}")

# Función para buscar un producto por su ID
def buscar_producto_por_id(inventario):
    try:
        id_buscar = int(input("Introduce el ID del producto a buscar: "))
        producto = inventario.get(id_buscar)
        if producto:
            print(f"ID: {producto.id_producto}, Nombre: {producto.nombre}, "
                  f"Cantidad: {producto.cantidad}, Precio Unitario: {producto.precio_unitario:.2f}")
        else:
            print(f"No se encontró ningún producto con ID {id_buscar}.")
    except ValueError:
        print("Por favor, ingresa un ID válido.")

# Función principal para manejar el menú de opciones
def menu():
    inventario = {}  # Diccionario para almacenar los productos, donde la clave es el ID del producto
    id_producto = 1  # El primer ID será 1, se incrementará automáticamente con cada producto ingresado

    while True:
        print("\nMenú de opciones:")
        print("1. Ingresar productos.")
        print("2. Mostrar inventario.")
        print("3. Buscar producto por ID.")
        print("4. Salir.")

        opcion = input("Selecciona una opción (1-4): ")

        if opcion == '1':
            ingresar_producto(inventario, id_producto)
            id_producto += 1  # Incrementar el ID para el siguiente producto
        elif opcion == '2':
            mostrar_inventario(inventario)
        elif opcion == '3':
            buscar_producto_por_id(inventario)
        elif opcion == '4':
            print("Saliendo del programa...")
            break
        else:
            print("Opción no válida, por favor selecciona una opción entre 1 y 4.")

# Ejecutar el programa
if __name__ == "__main__":
    menu()

""" Punto 2

**Análisis de Temperaturas en una Semana**
"""

def analizar_temperaturas():
    """
    Almacena las temperaturas de la semana, valida los datos y calcula promedios y suma.
    """
    temperaturas = []
    dias_semana = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]

    # Solicitar temperaturas al usuario y validarlas
    for dia in dias_semana:
        while True:
            try:
                temperatura = float(input(f"Ingrese la temperatura promedio para {dia}: "))
                if temperatura >= 0:
                    temperaturas.append(temperatura)
                    break
                else:
                    print("La temperatura debe ser un número positivo. Intente nuevamente.")
            except ValueError:
                print("Entrada inválida. Ingrese un número.")

    # Calcular promedios y suma
    promedio_pares = sum(temperaturas[i] for i in range(1, 7, 2)) / len(temperaturas[1::2])  # Martes (1), Jueves(3), Sábado(5)
    promedio_impares = sum(temperaturas[i] for i in range(0, 7, 2)) / len(temperaturas[::2])  # Lunes(0), Miércoles(2), Viernes(4), Domingo(6)
    suma_potencias = sum(temp**7 for temp in temperaturas)

    # Mostrar resultados
    print("\nResultados:")
    print(f"Promedio de temperaturas en días pares: {promedio_pares:.2f}")
    print(f"Promedio de temperaturas en días impares: {promedio_impares:.2f}")
    print(f"Suma de temperaturas elevadas a la 7ma potencia: {suma_potencias:.2f}")

# Ejecutar la función
analizar_temperaturas()